### ISSUE TITLE
Unable to publish draft 

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#176]
In profiles-dev, a user created a draft for "Eremophila forrestii subsp. forrestii", made several (unknown) changes, and tried to publish.

2 staged image files were left in the temp directory, but the references to them in the draft (staged-image attribute) were removed. This caused a null pointer when trying to publish.

Cause unknown.

```
2015-11-06 15:05:29,492 ERROR [GrailsExceptionResolver] NullPointerException occurred when processing request: [POST] /opus/foa/profile/f191e058-3f38-4c62-b9d4-0f5d0f954b6d/
toggleDraftMode
Cannot get property 'creator' on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot get property 'creator' on null object
        at au.org.ala.profile.hub.ImageService$_publishImages_closure5.doCall(ImageService.groovy:153)
        at au.org.ala.profile.hub.ImageService.publishImages(ImageService.groovy:147)
        at au.org.ala.profile.hub.ProfileController.toggleDraftMode(ProfileController.groovy:118)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at au.org.ala.cas.client.AlaHttpServletRequestWrapperFilter.doFilter(AlaHttpServletRequestWrapperFilter.java:66)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:197)
        at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:196)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:197)
        at org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:93)
        at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:197)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-8
