### ISSUE TITLE
Asking for Lower Level taxa for Bixa failed. It generated the pdf at genus level with just the generic selection.

Will try with another Genus shortly.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#205]
http://www.bugherd.com/projects/58735/tasks/139

**Comment by m-r-c** [comment]
```
2015-11-18 15:57:31,863 ERROR [JRFillSubreport] Fill 4: exception
net.sf.jasperreports.engine.util.JRFontNotFoundException: Font "comic sans ms" is not available to the JVM. See the Javadoc for more details.
	at net.sf.jasperreports.engine.fonts.FontUtil.checkAwtFont(FontUtil.java:360)
	at net.sf.jasperreports.engine.util.JRStyledText.getAwtAttributedString(JRStyledText.java:287)
	at net.sf.jasperreports.engine.fill.ComplexTextLineWrapper.start(ComplexTextLineWrapper.java:81)
	at net.sf.jasperreports.engine.fill.TextMeasurer.measure(TextMeasurer.java:539)

```

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-14

This change also addresses an XSS issue in the Profile Service and fixes some additional report generation problems, notably that tables don't appear by removing the option from the client (HTML sanitization will still allow it).

There is one remaining issue with report generation, which is that symbols do not appear in the PDF file.  There is a minimal sample that shows the problem and the fix here: TODO insert link to sample and is now tracked in this issue: TODO insert issue link here.
