### ISSUE TITLE
Uploaded (private) images disappear after removing the matched name

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#293]

**Comment by chrisala** [comment]
I couldn't reproduce this by:
1. Set collection config to not publish images automatically.
2. Attach image to a profile with a matched name.
3. Remove the name match.

**Comment by m-r-c** [comment]
Great...

This only happened once, while I was in the middle of a demo, so I didn't have a chance to look into it. The steps I took were:
1. In a public collection, with the "Do not push images to the public Atlas..." and "Only display images from approved image...." image options selected
1. Create a new profile with a matched name
1. Add an attribute & save & refresh
1. Add an image & save & refresh
1. Edit the name and change it to something that doesn't match
1. Save, let the page refresh -> image was gone.

**Comment by chrisala** [comment]
Thanks for the extra detail - I am still unable to reproduce this as described.  However when I was attempting to reproduce it, I did have my images disappear at one point, but I am fairly sure it was due to an exception thrown when attempting to retrieve images from the biocache.  This prevented any images from being returned.  Later all of my private images reappeared.

**Comment by chrisala** [comment]
Through luck I've reproduced this:
Cannot invoke method findResults() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method findResults() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at au.org.ala.profile.hub.ImageService.retrieveImages(ImageService.groovy:202)

**Comment by chrisala** [comment]
I've added a check to prevent this exception in the event of an unexpected response from the biocache image search.
https://upsource.ala.org.au/profiles/review/PRFLS-CR-48
